# Site settings
title: Steve Mayne's Piece of the Web
email: steve.mayne@gmail.com
author: Steve Mayne
description:
url: https://www.stevemayne.com

# Build settings
permalink: :title/
sass:
  sass_dir: css